In [1]:
import numpy as np

Basic Numpy arrays

multi-indexing

In [2]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a[[0, 3, 7, 9]]

array([0, 3, 7, 9])

Some Useful NumPy Functions

In [19]:
np.random.random(size=2)

array([0.46427623, 0.67779321])

In [23]:
np.random.normal(size=2)

array([-1.26691656, -0.46826565])

In [25]:
np.random.rand()

array([[0.74393852, 0.76166084, 0.98558501, 0.50368644],
       [0.24657048, 0.96102192, 0.75166097, 0.19219087]])

In [30]:
np.arange(10, 12, 0.3)

array([10. , 10.3, 10.6, 10.9, 11.2, 11.5, 11.8])

In [35]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [38]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.empty(4)

array([2.12199579e-314, 0.00000000e+000, 5.81021200e-321, 3.79442416e-321])

In [45]:
np.empty(5)

array([1.13838174e-311, 0.00000000e+000, 3.30035851e-321, 6.95250784e-310,
       0.00000000e+000])

In [46]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])